name: XML Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify XML Syntax with Python
      run: |
        python3 -c "
        import xml.etree.ElementTree as ET
        import sys
        try:
            ET.parse('custom_rules/sshd_rules.xml')
            print('XML yapısı geçerli!')
        except Exception as e:
            sys.exit(1)
        "

    # Yeni eklediğimiz kısım
    - name: Run Duplicate ID Check Script
      run: bash check_dupes.sh